classDiagram

class ALUMNO {
  +idAlumno
  +nombre
}

class EXAMEN {
  +idExamen
  +materia
}

class RENDIR_EXAMEN {
  +fecha
  +nota
}

ALUMNO "1" --> "0..*" RENDIR_EXAMEN
EXAMEN "1" --> "0..*" RENDIR_EXAMEN