classDiagram

class Libro {
  +ISBN
  +autor
  +titulo
}

class Usuario {
  +cedula
  +nombre
  +apellido
  +curso
  +matricula
  +registrarPrestamo()
}

class Categoria {
  +id_categoria
  +nombre
  +descripcion
  +filtrarLibros()
}

class Prestamo {
  +id_prestamo
  +fecha_prestamo
  +fecha_devolucion
  +registrarDevolucion()
}

%% Relaciones
Usuario "1" --> "0..*" Prestamo : realiza
Libro "1" --> "0..*" Prestamo : es prestado en
Categoria "1" --> "0..*" Libro : clasifica